/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, BigNumberish, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IKingInterface extends utils.Interface {
  contractName: "IKing";
  functions: {};

  events: {
    "NewKing(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewKing"): EventFragment;
}

export type NewKingEvent = TypedEvent<
  [string, string, BigNumber],
  { arg0: string; arg1: string; arg2: BigNumber }
>;

export type NewKingEventFilter = TypedEventFilter<NewKingEvent>;

export interface IKing extends BaseContract {
  contractName: "IKing";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IKingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "NewKing(address,address,uint256)"(
      arg0?: string | null,
      arg1?: string | null,
      arg2?: BigNumberish | null
    ): NewKingEventFilter;
    NewKing(
      arg0?: string | null,
      arg1?: string | null,
      arg2?: BigNumberish | null
    ): NewKingEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
