/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IKing, IKingInterface } from "../IKing";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "NewKing",
    type: "event",
  },
];

export class IKing__factory {
  static readonly abi = _abi;
  static createInterface(): IKingInterface {
    return new utils.Interface(_abi) as IKingInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IKing {
    return new Contract(address, _abi, signerOrProvider) as IKing;
  }
}
